---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args: [--branch, master]
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
    -   id: markdown-toc
-   repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
    -   id: sign-commit
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
    -   id: shellcheck
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
-   repo: https://github.com/sirosen/texthooks
    rev: 0.3.1
    hooks:
    -   id: fix-smartquotes
    -   id: fix-ligatures
-   repo: local
    hooks:
    #Use dotnet format already installed on your machine
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format worldboxpp.csproj --include
        types_or: ["c#", "vb"]
-   repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.4.0
    hooks:
    -   id: markdownlint-cli2
