# CircleCI configuration file
version: 2.1

jobs:
   deploy:
      docker:
      # Primary container image where all steps run
        - image: alpine
      steps:
        - checkout
        - command: |
          echo 'Creating .mod file';
          ls;
workflows:
  Build and deploy:
    jobs:
      - deploy