---

version: 2.1
orbs:
  windows: circleci/windows@4.1.1
jobs:
  sonarscan:
    executor:
      name: windows/default
    steps:
      - run:
          name: "Install Java"
          command: |

            function DownloadFile($url, $targetFile) {

                $uri = New-Object "System.Uri" "$url"
                $request = [System.Net.HttpWebRequest]::Create($uri)
                $request.set_Timeout(15000) #15 second timeout
                $response = $request.GetResponse()
                $totalLength = [System.Math]::Floor($response.get_ContentLength()/1024)
                $responseStream = $response.GetResponseStream()
                $targetStream = New-Object -TypeName System.IO.FileStream -ArgumentList $targetFile, Create
                $buffer = new-object byte[] 10KB
                $count = $responseStream.Read($buffer,0,$buffer.length)
                $downloadedBytes = $count

                while ($count -gt 0) {
                    $targetStream.Write($buffer, 0, $count)
                    $count = $responseStream.Read($buffer,0,$buffer.length)
                    $downloadedBytes = $downloadedBytes + $count
                    Write-Progress -activity "Downloading file '$($url.split('/') | Select -Last 1)'" -status "Downloaded ($([System.Math]::Floor($downloadedBytes/1024))K of $($totalLength)K): " -PercentComplete ((([System.Math]::Floor($downloadedBytes/1024)) / $totalLength)  * 100)
                }

                Write-Progress -activity "Finished downloading file '$($url.split('/') | Select -Last 1)'"
                $targetStream.Flush()
                $targetStream.Close()
                $targetStream.Dispose()
                $responseStream.Dispose()
            }

            Write-Output "Downloading Java"
            DownloadFile "https://download.oracle.com/java/18/latest/jdk-18_windows-x64_bin.exe" "./jdk-18_windows-x64_bin.exe"
            Write-Output "Installing Java"
            Start-Process 'jdk-18_windows-x64_bin.exe' /s
            Write-Output "Java installed."
      - run:
          name: "Install SonarScanner for .NET"
          command: |
            dotnet tool install --global dotnet-sonarscanner
      - checkout
      - run:
          name: "Replace Sonarqube project version"
          command: |
            (Get-Content sonar-project.properties) -replace '<VERSION>', $Env:VERSION | Out-File -encoding ASCII sonar-project.properties
            Get-Content ./sonar-project.properties
      - run:
          name: sonar-begin
          command: |
            URL="https://sonarcloud.io"
            dotnet sonarscanner begin /k:"worldboxpp" /d:sonar.host.url=$URL /d:sonar.login="${SONAR_TOKEN}" \
            /d:sonar.sources="/tmp/project" \
            /d:sonar.verbose=true \
            /o:"apolo49"
      - run:
          name: build-dll
          command: |
            dotnet build .
      - run:
          name: sonar-end
          command: |
            dotnet sonarscanner end /d:sonar.login=$Env:SONAR_TOKEN

  deploy:
    environment:
      RC_VERSION: 1
    docker:
      # Primary container image where all steps run
      - image: alpine
    steps:
      - checkout
      - run:
          name: State and list
          command: |
            echo 'Creating .mod file'
            ls
      - run:
          name: Version number
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]
            then
                sed -i -e "4 s/<VERSION>/${VERSION}/" mod.json
            elif [ "$CIRCLE_BRANCH" = "staging" ]
            then
                sed -i -e "4 s/<VERSION>/${VERSION}RC${RC_VERSION}/" mod.json
            elif [ ! -z "$CIRCLE_PULL_REQUEST" ]
            then
                sed -i -e "4 s/<VERSION>/${VERSION}RC${RC_VERSION}PR${CIRCLE_PULL_REQUEST##*/}/" mod.json
            else
                sed -i -e "4 s/<VERSION>/COM-${CIRCLE_SHA1}/" mod.json
            fi
      - run:
          name: Change structure
          command: |
            mkdir ./deploy
            echo 'Copying mod.json'
            cp mod.json ./deploy/mod.json
            echo 'Copying GameResources'
            cp -R ./GameResources ./deploy/GameResources
            echo 'Copying Embedded Resources'
            cp -R ./EmbeddedResources ./deploy/EmbeddedResources
            mkdir ./deploy/Code
            find ./Code -iname '*.cs' -exec sh -c 'echo "Copying" $1 && cp {} ./deploy/Code' - {} \;
      - run:
          name: Package files
          command: |
            apk add zip
            echo "Creating mod file"
            mkdir /artifacts
            cd deploy
            zip -r '/artifacts/Worldbox++.mod' .
      - store_artifacts:
          path: /artifacts
workflows:
  Build and deploy:
    jobs:
      - sonarscan:
          context: SonarCloud
      - deploy:
          requires:
            - sonarscan
