# CircleCI configuration file
version: 2.1

jobs:
   deploy:
      docker:
      # Primary container image where all steps run
        - image: alpine
      steps:
        - run: echo "Creating .mod file"
        - run: ls
workflows:
  Build and deploy:
    jobs:
      - deploy