---

version: 2.1
orbs:
  windows: circleci/windows@4.1.1
jobs:
  sonarscan:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Replace Sonarqube project version"
          command: |
            (Get-Content sonar-project.properties) -replace '<VERSION>', $Env:VERSION | Out-File -encoding ASCII sonar-project.properties
            Get-Content ./sonar-project.properties
      - run:
          name: Install Rust
          command: |
            Invoke-WebRequest -Uri https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe -outfile "C:\rustup.exe"
            C:\rustup.exe -y
      - run:
          name: Download SteamCMD
          command: |
            New-Item -Path "C:\" -Name "steamcmd" -ItemType "directory"
            Invoke-WebRequest -Uri https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip -outfile "C:\steamcmd.zip"
            Expand-Archive -LiteralPath "C:\steamcmd.zip" -DestinationPath "C:\steamcmd"
            git clone https://github.com/weilbyte/steamcmd-2fa C:/steamcmd-2fa
            cargo build C:/steamcmd-2fa
            ls C:/steamcmd-2fa
      - run:
          name: Download WorldBox
          command: |
            C:\steamcmd\steamcmd-2fa --path . --username $Env:STEAM1 --password $Env:STEAM2 --secret $Env:STEAM3 --args "+force_install_dir C:\worldbox +app_update 1206560 validate +quit"
      - run:
          name: Download NCMS
          command: |
            New-Item -Path "C:\" -Name "NCMS" -ItemType "directory"
            Invoke-WebRequest -Uri https://denq04.github.io/ncms/static/files/ncms/ncms.1.5.1.zip -outfile "C:\ncms.zip"
            Expand-Archive -LiteralPath "C:\ncms.zip" -DestinationPath "C:\ncms"
      - run:
          name: "Install SonarScanner for .NET"
          command: |
            dotnet tool install --global dotnet-sonarscanner
      - run:
          name: sonar-begin
          command: |
            $URL = "https://sonarcloud.io"
            dotnet sonarscanner begin /k:"worldboxpp" /d:sonar.host.url=$URL /d:sonar.login=$Env:SONAR_TOKEN /d:sonar.sources="/tmp/project" /d:sonar.verbose=true /o:"apolo49"
      - run:
          name: build-dll
          command: |
            dotnet restore ./worldboxpp.csproj
            dotnet build .
      - run:
          name: sonar-end
          command: |
            dotnet sonarscanner end /d:sonar.login=$Env:SONAR_TOKEN

  deploy:
    environment:
      RC_VERSION: 1
    docker:
      # Primary container image where all steps run
      - image: alpine
    steps:
      - checkout
      - run:
          name: State and list
          command: |
            echo 'Creating .mod file'
            ls
      - run:
          name: Version number
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]
            then
                sed -i -e "4 s/<VERSION>/${VERSION}/" mod.json
            elif [ "$CIRCLE_BRANCH" = "staging" ]
            then
                sed -i -e "4 s/<VERSION>/${VERSION}RC${RC_VERSION}/" mod.json
            elif [ ! -z "$CIRCLE_PULL_REQUEST" ]
            then
                sed -i -e "4 s/<VERSION>/${VERSION}RC${RC_VERSION}PR${CIRCLE_PULL_REQUEST##*/}/" mod.json
            else
                sed -i -e "4 s/<VERSION>/COM-${CIRCLE_SHA1}/" mod.json
            fi

      - run:
          name: Change structure
          command: |
            mkdir ./deploy
            echo 'Copying mod.json'
            cp mod.json ./deploy/mod.json
            echo 'Copying GameResources'
            cp -R ./GameResources ./deploy/GameResources
            echo 'Copying Embedded Resources'
            cp -R ./EmbeddedResources ./deploy/EmbeddedResources
            mkdir ./deploy/Code
            find ./Code -iname '*.cs' -exec sh -c 'echo "Copying" $1 && cp {} ./deploy/Code' - {} \;
      - run:
          name: Package files
          command: |
            apk add zip
            echo "Creating mod file"
            mkdir /artifacts
            cd deploy
            zip -r '/artifacts/Worldbox++.mod' .
      - store_artifacts:
          path: /artifacts
workflows:
  Build and deploy:
    jobs:
      - sonarscan:
          context: SonarCloud
      - deploy:
          requires:
            - sonarscan
